import type { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import styles from "styles/Home.module.css";
import { Gallery } from "modules/Gallery";
import { Franchise } from "modules/Franchise";
import { RichText } from "modules/RichText";
import { Copy } from "modules/Copy";
import { getHomePage, type HomeProps } from "lib/strapi";

export default function Home(props: HomeProps["data"]["attributes"]) {
  return (
    <>
      <Head>
        <title>{props.Title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {props.Sections.map((section) => {
          switch (section.__component) {
            case "common.copy":
              return <Copy key={section.id} {...section} />;
            case "common.rich-text":
              return <RichText key={section.id} {...section} />;
            case "common.franchise":
              return <Franchise key={section.id} {...section} />;
            case "common.gallery": {
              return <Gallery key={section.id} {...section} />;
            }
            default:
              return null;
          }
        })}
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps<
  HomeProps["data"]["attributes"]
> = async (props) => {
  const response = await getHomePage(props.locale);

  return {
    props: response.data.attributes,
    revalidate: 30,
  };
};
